#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#define unsigned long long ull
#define unsigned long ul
#define unsigned int ui
#define long long ll
#define const char cc
#define unsigned char uc

uc pci_bus_max_busnr(struct pci_bus *bus);
int pci_find_capability(struct pci_dev *dev, int cap);
int pci_bus_find_capability(struct pci_bus *bus, unsigned int devfn, int cap);
int pci_find_next_ext_capability(struct pci_dev *dev, int start, int cap);
int pci_find_ext_capability(struct pci_dev *dev, int cap);
int pci_find_next_ht_capability(struct pci_dev *dev, int pos, int ht_cap);
int pci_find_ht_capability(struct pci_dev *dev, int ht_cap);
struct resource *pci_find_parent_resource(const struct pci_dev *dev, struct resource *res);
struct resource *pci_find_resource(struct pci_dev *dev, struct resource *res);
struct pci_dev *pci_find_pcie_root_port(struct pci_dev *dev);
int __pci_complete_power_transition(strut pci_dev *dev, pci_power_t state);
int pci_set_power_state(struct pci_dev *dev, pci_power_t state);
pci_power_t pci_choose_state(struct pci_dev *dev, pm_message_t state);
int pci_save_state(struct pci_dev *dev);
void pci_restore_state(struct pci_dev *dev);
struct pci_saved_state* pci_store_saved_state (pci_store_saved_statestruct pci_dev * dev);
int pci_load_saved_state (pci_load_saved_statestruct pci_dev * dev, struct pci_saved_state * state);
int pci_load_and_free_saved_state (pci_load_and_free_saved_statestruct pci_dev * dev, struct pci_saved_state ** state);
int pci_reenable_device (pci_reenable_devicestruct pci_dev * dev);
int pci_enable_device_io (pci_enable_device_iostruct pci_dev * dev);
int pci_enable_device_mem (pci_enable_device_memstruct pci_dev * dev);
int pci_enable_device (pci_enable_devicestruct pci_dev * dev);
int pcim_enable_device (pcim_enable_devicestruct pci_dev * pdev);
void pcim_pin_device (pcim_pin_devicestruct pci_dev * pdev);
void pci_disable_device (pci_disable_devicestruct pci_dev * dev);

int pci_set_pcie_reset_state (pci_set_pcie_reset_statestruct pci_dev * dev, enum pcie_reset_state state);
bool pci_pme_capable (pci_pme_capablestruct pci_dev * dev, pci_power_t state);
void pci_pme_active (pci_pme_activestruct pci_dev * dev, bool enable);
int __pci_enable_wake(struct pci_dev *dev, pci_power_t state, bool runtime, bool enable);
int pci_wake_from_d3(struct pci_dev *dev, bool enable);
int pci_prepare_to_sleep(struct pci_dev * dev);
int pci_back_from_sleep (pci_back_from_sleepstruct pci_dev * dev);
bool pci_dev_run_wake (pci_dev_run_wakestruct pci_dev * dev);
void pci_d3cold_enable (pci_d3cold_enablestruct pci_dev * dev);
void pci_d3cold_disable (pci_d3cold_disablestruct pci_dev * dev);
u8 pci_common_swizzle (pci_common_swizzlestruct pci_dev * dev, u8 * pinp);
void pci_release_region (pci_release_regionstruct pci_dev * pdev, int bar);
int pci_request_region (pci_request_regionstruct pci_dev * pdev, int bar, const char * res_name);
int pci_request_region_exclusive (pci_request_region_exclusivestruct pci_dev * pdev, int bar, const char * res_name);
void pci_release_selected_regions (pci_release_selected_regionsstruct pci_dev * pdev, int bars);
int pci_request_selected_regions (pci_request_selected_regionsstruct pci_dev * pdev, int bars, const char * res_name);
void pci_release_regions (pci_release_regionsstruct pci_dev * pdev);
int pci_request_regions (pci_request_regionsstruct pci_dev * pdev, const char * res_name);
int pci_request_regions_exclusive (pci_request_regions_exclusivestruct pci_dev * pdev,	const char * res_name);
void pci_set_master (pci_set_masterstruct pci_dev * dev);
void pci_clear_master (pci_clear_masterstruct pci_dev * dev);
int pci_set_cacheline_size (pci_set_cacheline_sizestruct pci_dev * dev);
int pci_set_mwi (pci_set_mwistruct pci_dev * dev);
void pci_clear_mwi (pci_clear_mwistruct pci_dev * dev);
int pci_try_set_mwi (pci_try_set_mwistruct pci_dev * dev);
void pci_intx (pci_intxstruct pci_dev * pdev, int enable);
bool pci_intx_mask_supported (pci_intx_mask_supportedstruct pci_dev * dev);
bool pci_check_and_mask_intx (pci_check_and_mask_intxstruct pci_dev * dev);
bool pci_check_and_unmask_intx (pci_check_and_unmask_intxstruct pci_dev * dev);
int pci_wait_for_pending_transaction (pci_wait_for_pending_transactionstruct pci_dev * dev);
void pci_reset_bridge_secondary_bus (pci_reset_bridge_secondary_busstruct pci_dev * dev) ;
int __pci_reset_function (__pci_reset_functionstruct pci_dev * dev);
int __pci_reset_function_locked (__pci_reset_function_lockedstruct pci_dev * dev);
int pci_reset_function (pci_reset_functionstruct pci_dev * dev);
int pci_try_reset_function (pci_try_reset_functionstruct pci_dev * dev);
int pci_probe_reset_slot (pci_probe_reset_slotstruct pci_slot * slot);
int pci_reset_slot (pci_reset_slotstruct pci_slot * slot);
int pci_try_reset_slot (pci_try_reset_slotstruct pci_slot * slot);
int pci_probe_reset_bus (pci_probe_reset_busstruct pci_bus * bus);
int pci_reset_bus (pci_reset_busstruct pci_bus * bus);
int pci_try_reset_bus (pci_try_reset_busstruct pci_bus * bus);
int pcix_get_max_mmrbc (pcix_get_max_mmrbcstruct pci_dev * dev);
int pcix_get_mmrbc (pcix_get_mmrbcstruct pci_dev * dev);
int pcix_set_mmrbc (pcix_set_mmrbcstruct pci_dev * dev ,	int mmrbc);
int pcie_get_readrq (pcie_get_readrqstruct pci_dev * dev);
int pcie_set_readrq (pcie_set_readrqstruct pci_dev * dev, int rq);
int pcie_get_mps (pcie_get_mpsstruct pci_dev * dev);
int pcie_set_mps (pcie_set_mpsstruct pci_dev * dev,	int mps);
int pcie_get_minimum_link (pcie_get_minimum_linkstruct pci_dev * dev, enum pci_bus_speed * speed, enum pcie_link_width * width);
int pci_select_bars (pci_select_barsstruct pci_dev * dev,		unsigned long flags);
int pci_add_dynid (pci_add_dynidstruct pci_driver * drv, unsigned int vendor, signed int device, ui subvendor, ui subdevice, ui class, ui class_mask, ul driver_data);
const struct pci_device_id *pci_match_id(const struct pci_device_id *ids, struct pci_dev *dev);
void pci_unregister_driver(struct pci_driver *drv);
int __pci_register_driver (__pci_register_driverstruct pci_driver * drv, struct module * owner, const char * mod_name);
struct pci_driver * pci_dev_driver (pci_dev_driverconst struct pci_dev * dev);
struct pci_dev * pci_dev_get (pci_dev_getstruct pci_dev * dev);
void pci_dev_put (pci_dev_putstruct pci_dev * dev);
void pci_stop_and_remove_bus_device (pci_stop_and_remove_bus_devicestruct pci_dev * dev);
struct pci_bus * pci_find_bus (pci_find_busint domain,	int busnr);
struct pci_bus * pci_find_next_bus (pci_find_next_busconst struct pci_bus * from);
struct pci_dev * pci_get_slot (pci_get_slotstruct pci_bus * bus, unsigned int devfn);
struct pci_dev * pci_get_domain_bus_and_slot (pci_get_domain_bus_and_slotint domain, ui bus, ui devfn);
struct pci_dev * pci_get_subsys (pci_get_subsysunsigned int vendor, ui device, ui ss_vendor, ui ss_device, struct pci_dev *from);
struct pci_dev * pci_get_device (pci_get_deviceunsigned int vendor, unsigned int device, struct pci_dev * from);
struct pci_dev * pci_get_class (pci_get_classunsigned int class,	struct pci_dev * from);
int pci_dev_present (pci_dev_presentconst struct pci_device_id * ids);
void pci_msi_mask_irq (pci_msi_mask_irqstruct irq_data * data);

void pci_msi_unmask_irq (pci_msi_unmask_irqstruct irq_data * data);
int pci_msi_vec_count (pci_msi_vec_countstruct pci_dev * dev);
int pci_msix_vec_count (pci_msix_vec_countstruct pci_dev * dev);
int pci_enable_msix (pci_enable_msixstruct pci_dev * dev, struct msix_entry * entries, int nvec);
int pci_msi_enabled (pci_msi_enabledvoid);
int pci_enable_msix_range (pci_enable_msix_rangestruct pci_dev * dev, struct msix_entry * entries, int minvec, int maxvec);
int pci_alloc_irq_vectors_affinity (pci_alloc_irq_vectors_affinitystruct pci_dev * dev, unsigned int min_vecs,	unsigned int max_vecs, unsigned int flags,	const struct irq_affinity * affd);
void pci_free_irq_vectors (pci_free_irq_vectorsstruct pci_dev * dev);
int pci_irq_vector (pci_irq_vectorstruct pci_dev * dev,		unsigned int nr);
const struct cpumask * pci_irq_get_affinity (pci_irq_get_affinitystruct pci_dev * dev, int nr);
int pci_irq_get_node (pci_irq_get_nodestruct pci_dev * pdev, int vec);
struct irq_domain * pci_msi_create_irq_domain (pci_msi_create_irq_domainstruct fwnode_handle * fwnode, struct msi_domain_info * info,		struct irq_domain * parent);
int pci_bus_alloc_resource (pci_bus_alloc_resourcestruct pci_bus * bus, struct resource * res, resource_size_t size, resource_size_t align, resource_size_t min,	unsigned long type_mask,	resource_size_t (*alignf) (void *, const struct resource *, resource_size_t, resource_size_t), void * alignf_data);
void pci_bus_add_device (pci_bus_add_devicestruct pci_dev * dev);
void pci_bus_add_devices (pci_bus_add_devicesconst struct pci_bus * bus);
struct pci_ops * pci_bus_set_ops (pci_bus_set_opsstruct pci_bus * bus, struct pci_ops * ops);
ssize_t pci_read_vpd (pci_read_vpdstruct pci_dev * dev,		loff_t pos,		size_t count, void * buf);
ssize_t pci_write_vpd (pci_write_vpdstruct pci_dev * dev, loff_t pos,		size_t count,		const void * buf);
int pci_set_vpd_size (pci_set_vpd_sizestruct pci_dev * dev, size_t len);
void pci_cfg_access_lock (pci_cfg_access_lockstruct pci_dev * dev);
bool pci_cfg_access_trylock (pci_cfg_access_trylockstruct pci_dev * dev);
void pci_cfg_access_unlock (pci_cfg_access_unlockstruct pci_dev * dev);
enum pci_lost_interrupt_reason pci_lost_interrupt (pci_lost_interruptstruct pci_dev * pdev);
int __ht_create_irq (__ht_create_irqstruct pci_dev * dev, int idx, ht_irq-update_t *update);
int ht_create_irq(struct pci_dev *dev, int idx);
void ht_destroy_irq (ht_destroy_irqunsigned int irq);
int pci_scan_slot (pci_scan_slotstruct pci_bus * bus, int devfn);
unsigned int pci_rescan_bus (pci_rescan_busstruct pci_bus * bus);
struct pci_slot * pci_create_slot (pci_create_slotstruct pci_bus * parent, int slot_nr, cc *name, struct hotplug_slot *hotplug);
void pci_destroy_slot(struct pci_slot *slot);
void pci_hp_create_module_link(struct pci_slot *pci_slot);
void pci_hp_remove_module_link (pci_hp_remove_module_linkstruct pci_slot * pci_slot);
int pci_enable_rom (pci_enable_romstruct pci_dev * pdev);
void pci_disable_rom (pci_disable_romstruct pci_dev * pdev);
void __iomem * pci_map_rom (pci_map_romstruct pci_dev * pdev, size_t *size);
void pci_unmap_rom (pci_unmap_romstruct pci_dev * pdev, void __iomem * rom);
void __iomem * pci_platform_rom (pci_platform_romstruct pci_dev * pdev, size_t * size);
int pci_enable_sriov (pci_enable_sriovstruct pci_dev * dev, int nr_virtfn);
void pci_disable_sriov (pci_disable_sriovstruct pci_dev * dev);
int pci_num_vf (pci_num_vfstruct pci_dev * dev);
int pci_vfs_assigned (pci_vfs_assignedstruct pci_dev * dev);
int pci_sriov_set_totalvfs (pci_sriov_set_totalvfsstruct pci_dev * dev,		u16 numvfs);
int pci_sriov_get_totalvfs (pci_sriov_get_totalvfsstruct pci_dev * dev);
ssize_t pci_read_legacy_io (pci_read_legacy_iostruct file * filp, struct kobject * kobj, struct bin_attribute * bin_attr, char *buf,	loff_t off, size_t count);
ssize_t pci_write_legacy_io (pci_write_legacy_iostruct file * filp,		struct kobject * kobj,	struct bin_attribute * bin_attr, char * buf, loff_t off, size_t count);
int pci_mmap_legacy_mem (pci_mmap_legacy_memstruct file * filp,		struct kobject * kobj,kobjstruct bin_attribute * attr,	struct vm_area_struct * vma);
int pci_mmap_legacy_io (pci_mmap_legacy_iostruct file * filp,		struct kobject * kobj, struct bin_attribute * attr, struct vm_area_struct * vma);
void pci_adjust_legacy_attr (pci_adjust_legacy_attrstruct pci_bus * b,	enum pci_mmap_state mmap_type);
void pci_create_legacy_files (pci_create_legacy_filesstruct pci_bus * b);
int pci_mmap_resource (pci_mmap_resourcestruct kobject * kobj,	struct bin_attribute * attr, struct vm_area_struct * vma, int write_combine);
void pci_remove_resource_files (pci_remove_resource_filesstruct pci_dev * pdev);
int pci_create_resource_files (pci_create_resource_filesstruct pci_dev * pdev);
ssize_t pci_write_rom (pci_write_romstruct file * filp, struct kobject * kobj,	struct bin_attribute * bin_attr, char * buf,	loff_t off,		size_t count);
ssize_t pci_read_rom (pci_read_romstruct file * filp, struct kobject * kobj,, struct bin_attribute * bin_attr,	char * buf, loff_t off, size_t count);
void pci_remove_sysfs_dev_files (pci_remove_sysfs_dev_filesstruct pci_dev * pdev);

